import type { AppData } from './types'
import { generateId } from './utils'

export function generateSeedData(): AppData {
  const now = new Date().toISOString()
  const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString().split('T')[0]

  return {
    menu: [
      {
        id: generateId(),
        name: 'Colombia Gesha Filter',
        price: 180,
        category: 'Brewed/Filter Coffee',
        autoDecide: 'hot',
        beanId: 'bean-1',
        active: true,
        recipe: { dose: 18, water: 300, temp: 93 },
        createdAt: now,
      },
      {
        id: generateId(),
        name: 'Ethiopia Uraga Filter',
        price: 160,
        category: 'Brewed/Filter Coffee',
        autoDecide: 'hot',
        beanId: 'bean-3',
        active: true,
        recipe: { dose: 18, water: 300, temp: 92 },
        createdAt: now,
      },
      {
        id: generateId(),
        name: 'Black Meridian Espresso',
        price: 120,
        category: 'Espresso Drinks',
        autoDecide: 'hot',
        beanId: 'bean-2',
        active: true,
        recipe: { dose: 19, espressoYield: 45, temp: 94 },
        createdAt: now,
      },
      {
        id: generateId(),
        name: 'Black Meridian Americano',
        price: 140,
        category: 'Espresso Drinks',
        autoDecide: 'hot',
        beanId: 'bean-2',
        active: true,
        recipe: { dose: 19, espressoYield: 45, water: 150, temp: 94 },
        createdAt: now,
      },
      {
        id: generateId(),
        name: 'Black Meridian Iced Latte',
        price: 160,
        category: 'Iced Coffee Drinks',
        autoDecide: 'ice',
        beanId: 'bean-2',
        active: true,
        recipe: { dose: 19, espressoYield: 45, ice: 120, milk: 150, temp: 94 },
        createdAt: now,
      },
      {
        id: generateId(),
        name: 'Colombia Gesha Iced Pour-over',
        price: 200,
        category: 'Iced Coffee Drinks',
        autoDecide: 'ice',
        beanId: 'bean-1',
        active: true,
        recipe: { dose: 22, water: 250, ice: 120, temp: 93 },
        createdAt: now,
      },
    ],
    beans: [
      {
        id: 'bean-1',
        name: 'Colombia Gesha Inmaculada',
        origin: 'Colombia',
        variety: 'Gesha',
        process: 'Washed',
        group: 'P',
        costPerGram: 0.35,
        stockGrams: 150,
        altitude: 2100,
        roastLevel: 20,
        roastDate: daysAgo(7),
        tastingNotes: { floral: ['jasmine', 'orange blossom'], fruity: ['bergamot', 'lemon', 'peach'], sweet: ['honey'], nutty: [], spicy: [], fermented: [], other: ['tea-like'] },
        createdAt: now,
      },
      {
        id: 'bean-2',
        name: 'Thailand ใจพรือโ้้ฉ้ Black Meridian Espresso Blend',
        origin: 'Thailand',
        process: 'Washed',
        group: 'C',
        costPerGram: 0.12,
        stockGrams: 500,
        altitude: 1100,
        roastLevel: 63,
        roastDate: daysAgo(3),
        tastingNotes: { floral: [], fruity: ['dark cherry'], sweet: ['dark chocolate', 'caramel'], nutty: ['hazelnut', 'almond'], spicy: ['cinnamon'], fermented: [], other: ['tobacco'] },
        createdAt: now,
      },
      {
        id: 'bean-3',
        name: 'Ethiopia Uraga Storm Seeker WHO R U blend',
        origin: 'Ethiopia',
        variety: 'Ethiopian Heirloom',
        process: 'Natural',
        group: 'P',
        costPerGram: 0.25,
        stockGrams: 300,
        altitude: 1900,
        roastLevel: 20,
        roastDate: daysAgo(5),
        tastingNotes: { floral: ['lavender'], fruity: ['blueberry', 'strawberry', 'pineapple'], sweet: ['maple syrup'], nutty: [], spicy: [], fermented: ['wine'], other: [] },
        createdAt: now,
      },
    ],
    transactions: [
      { id: generateId(), date: daysAgo(7), beanId: 'bean-1', beanName: 'Colombia Gesha Inmaculada', type: 'purchase', quantity: 100, costPerGram: 4.4, totalCost: 440, note: '100g @ 4.4/g = 440 THB', createdAt: now },
      { id: generateId(), date: daysAgo(5), beanId: 'bean-1', beanName: 'Colombia Gesha Inmaculada', type: 'purchase', quantity: 50, costPerGram: 4.4, totalCost: 220, note: '50g @ 4.4/g = 220 THB', createdAt: now },
      { id: generateId(), date: daysAgo(14), beanId: 'bean-2', beanName: 'Thailand Black Meridian Espresso Blend', type: 'purchase', quantity: 500, costPerGram: 0.12, totalCost: 60, note: 'Initial purchase', createdAt: now },
      { id: generateId(), date: daysAgo(10), beanId: 'bean-3', beanName: 'Ethiopia Uraga Storm Seeker WHO R U blend', type: 'purchase', quantity: 100, costPerGram: 0.25, totalCost: 25, note: 'Initial purchase', createdAt: now },
      { id: generateId(), date: daysAgo(8), beanId: 'bean-3', beanName: 'Ethiopia Uraga Storm Seeker WHO R U blend', type: 'purchase', quantity: 200, costPerGram: 0.22, totalCost: 44, note: 'Restock', createdAt: now },
    ],
    runs: [],
    purchaseOrders: [],
    fundingSources: [],
    activeRunId: null,
    mode: 'operational',
  }
}
